#######################################################
## Input data and prefix ##
#######################################################
##### THESE ARE THE FILES TO SPECIFY FOR EACH SAMPLE ##
bam: "tmp.bam"
bai: "tmp.bai"
vcf: "tmp.vcf"
outdir : "results"
OUTPREFIX: "postprocess"

#######################################################
## Overall reference resources
#######################################################
ref: "hsapiens.hs37d5.fasta"
ref_fai: "hsapiens.hs37d5.fasta.fai"
ref_dict: "hsapiens.hs37d5.dict"
repmask_bed: "../resources/hg19/repmasker_hg19.bed.gz"
intron_bed: "../resources/hg19/ens_intron_hg19_slice_4bp.bed.gz"
rnaedit_bed: "../resources/hg19/merged_RNA_edit.bed.gz"
model: "SmartRNASeqCaller/resources/RNA_Variant_RF_model.rds"

## paths to tools [docker image paths]
GATK: "/usr/GenomeAnalysisTK.jar"
python:  "/opt/conda/bin/python2.7" 
#Full Path to SmartRNASeqCaller (in docker image: /opt/SmartRNASeqCaller or
# Locally : your path to SmartRNASeqCaller
pp_path: "../SmartRNASeqCaller"

